jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      USERNAME: ${{ github.repository_owner }}
      CUSTOM_VAR: 'my_custom_value' # Ejemplo de variable de entorno personalizada

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Profile 3D Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      
      - name: Set Commit Message
        id: set_commit_message
        run: echo "::set-output name=message::Generated commit message"
        shell: bash
      
      - name: Commit & Push
        env:
          COMMIT_MESSAGE: ${{ steps.set_commit_message.outputs.message }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "${COMMIT_MESSAGE}"
          git push
