name: GitHub-Profile-3D-Contrib

on:
  schedule: # 20:00 CET/CEST == 18:00 UTC
    - cron: "0 20 * * *"
  workflow_dispatch:
    inputs:
      custom-message:
        description: 'Custom message for commit'
        required: false
        default: 'generated'

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      USERNAME: ${{ github.repository_owner }}
      CUSTOM_VAR: 'my_custom_value' # Ejemplo de variable de entorno personalizada

    steps:
      - uses: actions/checkout@v3
      - name: Generate GitHub Profile 3D Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "${COMMIT_MESSAGE}"
          git push
     
